
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/services
    ports:
      - "6789:6789"
    environment:
      - PORT=6789
    command: ["node", "main.mjs"]